option:
  0: 
    name: Quit
    func: "exit 1"
  1: 
    name: Backup
    func: backup
  2: 
    name: Mount
    func: "mountFstab"
  3:
    name: VPN
    func: "menu option_3_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: VPN Connect
        func: "vpn connectSugar"
      2:
        name: VPN Kill
        func: "vpn kill"

  4:
    name: Git Config
    func: "menu option_4_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: Global email and username
        func: "gitConfig global"
  5:
    name: xbuild
    func: "xbuild"
  6:
    name: Git Mango
    func: "menu option_6_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: clone
        func: "gitMango clone"
      2:
        name: post checkout
        func: "gitMango postCheckout"
      3:
        name: patch
        func: "gitMango patch"
  7:
    name: Import SQL Dump
    func: "importSQLDump"
  8:
    name: vagrantON
    func: "menu option_8_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: clone
        func: vagrantON clone
      2:
        name: status
        func: vagrantON status
      3:
        name: up
        func: vagrantON up
      4:
        name: ssh
        func: vagrantON ssh
      5:
        name: resume
        func: vagrantON resume
      6:
        name: suspend
        func: vagrantON suspend
      7:
        name: destroy
        func: vagrantON destroy
  9:
    name: System Info
    func: "menu option_9_opt"
    opt:
      0:
        name: Main menu
        func: menu option
      1:
        name: Full info
        func: sysInfo
      2:
        name: OS
        func: sysInfo OS
      3:
        name: disk
        func: sysInfo disk
      4:
        name: Actual folder size
        func: sysInfo foldersSize
      5:
        name: Actual folder write benchmark
        func: sysInfo writeTest
      6:
        name: Top 10 sub-folders size
        func: sysInfo top10folders

git:
  user:
    name: "Your Name"
    email: "email@domain.com"
  clone:
    mango:
      origin:   git@github.com:svnvcristea/Mango.git
      upstream: git@github.com:ps-dev-lapp/Mango.git
vpn:
  conf: /etc/vpnc/sugarvpn.conf

mount:
  fstab:
    0: "192.168.56.101:/srv/www/htdocs"
    1: "192.168.56.101:/etc/apache2/vhosts.d"
  
backup:
  serverip: 192.168.99.10
  mountpoint: "/mnt/BackupSynk"
  path: "$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  command:
    mount: mount.cifs
    umount: umount
    rsync: grsync
    domain: DOMAIN1
    username: user.name

xbuild:
  flav: ent
  version: 7.5.0
  license: 'salesa8fb331009c9f0902d19c8edemo'
  db:
    user: root
    password: root
    host: localhost
    type: mysql
    demoData: no
  rootPath: /srv/www/htdocs
  repo:
    0:
      name: sugar-qa
      url: qa.sugar.dev
      path: /srv/git-repo/jpm-mango
      flav: ent
      version: 7.6.1.0
      db:
        user: system
        password: manager
        host: localhost
        type: oci8
        demoData: yes
    1:
      name: agfa
      url: agfa.dev
      path: /srv/www/git-repo/agfa-mango
      flav: ent
      version: 7.5.1.0
    2:
      name: lapp
      url: lapp.dev
      path: /srv/www/git-repo/lapp-mango
  dbContent:
    email_addresses:
      0:
        id: a63521a9-bd97-d920-0d7a-5469e10a862a
        email_address: admin@sugarcrm.com
        email_address_caps: ADMIN@SUGARCRM.COM
        invalid_email: 0
        opt_out: 0
        date_created: "2015-09-07 12:00:12"
        date_modified: "2015-09-07 12:00:12"
        deleted: 0
    email_addr_bean_rel:
      0:
        id: a60ff377-d03b-6cca-8ca1-5469e19ae22e
        email_address_id: a63521a9-bd97-d920-0d7a-5469e10a862a
        bean_id: 1
        bean_module: Users
        primary_address: 1
        reply_to_address: 0
        date_created: "2015-09-07 12:00:12"
        date_modified: "2015-09-07 12:00:12"
        deleted: 0
mysql:
  host: localhost
  user: root
  pass: root

vagrantON:
  repo: git@github.com:svnvcristea/vagrantON.git
  path: ./
  stack: php54