encode:
  sudo:
    use: true

git:
  # the local git folder path where most of the repositories will be cloned into
  path: /home/git-repo
  user:
    name: "Your Name"
    email: "email@softvision.ro"
  clone:
    mango:
      origin:   git@github.com:svnvcristea/Mango.git
      upstream: git@github.com:ps-dev-lapp/Mango.git
  GitHub:
    keys: "mango sugarBash SugarCRMCodeSniffer stacks stackDeployer vagrantON toolshed"
    mango: git@github.com:svnvcristea/Mango.git
    sugarBash: git@github.com:svnvcristea/sugarBash.git
    SugarCRMCodeSniffer: git@github.com:svnvcristea/SugarCRMCodeSniffer.git
    stacks: git@github.com:svnvcristea/stacks.git
    stackDeployer: git@github.com:svnvcristea/stack-deployer.git
    vagrantON: git@github.com:svnvcristea/vagrantON.git
    toolshed: git@github.com:sugarcrm/toolshed.git

vpn:
  conf: /etc/vpnc/sugarvpn.conf

mount:
  fstab:
    SugarEPS:
      0: "192.168.56.101:/srv/www/htdocs"
      1: "192.168.56.101:/etc/apache2/vhosts.d"
    php54:
      0: "192.168.56.14:/var/www/html"

backup:
  serverip: 192.168.99.10
  mountpoint: "/mnt/BackupSynk"
  path: "$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  command:
    mount: mount.cifs
    umount: umount
    rsync: grsync
    domain: DOMAIN1
    username: user.name

db:
  mysql:
    connect:
      host: localhost
      user: root
      pass: sugarcrm
    setRoot:
      host: %
      user: root
      pass: pspass

vagrantON:
  repo: git@github.com:svnvcristea/vagrantON.git
  path: ~/git-repo
  stack: php54

day:
  on:
    0: "von resume"
    1: /mnt/ssd/PhpStorm/bin/phpstorm.sh
    2: skype
    3: hipchat
    4: thunderbird
    5: firefox
    6: /usr/bin/google-chrome-stable
    7: "vlc /home/nicolaecristea/play.pls"
    8: "git -C /home/nicolaecristea/git-repo/jpm-mango fetch --all"
  off:
    0: "von suspend"
    1: "bash $0 1"